services:
  app:
    image: paibl/gemini-breeding:latest  # Named image for reuse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # React frontend (external:internal)
      - "5000:5000"  # Flask backend (external:internal)
      - "8091:8091"  # Tile server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Docker-in-Docker
      - ~/GEMINI-App-Data:/root/GEMINI-App-Data  # Mount host data to container data directory
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
