// This file is auto-generated by @hey-api/openapi-ts

export const AppSettingPublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 4096,
            title: 'Value'
        }
    },
    type: 'object',
    required: ['key', 'value'],
    title: 'AppSettingPublic'
} as const;

export const AppSettingUpdateSchema = {
    properties: {
        value: {
            type: 'string',
            maxLength: 4096,
            title: 'Value'
        }
    },
    type: 'object',
    required: ['value'],
    title: 'AppSettingUpdate'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ConvertGeoTiffRequestSchema = {
    properties: {
        file_path: {
            type: 'string',
            title: 'File Path'
        }
    },
    type: 'object',
    required: ['file_path'],
    title: 'ConvertGeoTiffRequest'
} as const;

export const ExecuteStepRequestSchema = {
    properties: {
        step: {
            type: 'string',
            title: 'Step'
        },
        models: {
            items: {
                '$ref': '#/components/schemas/ModelConfig'
            },
            type: 'array',
            title: 'Models',
            default: []
        },
        agrowstitch_version: {
            type: 'integer',
            title: 'Agrowstitch Version',
            default: 1
        },
        ortho_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ortho Name'
        },
        ortho_version: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ortho Version'
        },
        boundary_version: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Boundary Version'
        }
    },
    type: 'object',
    required: ['step'],
    title: 'ExecuteStepRequest'
} as const;

export const FileUploadCreateSchema = {
    properties: {
        data_type: {
            type: 'string',
            maxLength: 100,
            title: 'Data Type'
        },
        experiment: {
            type: 'string',
            maxLength: 255,
            title: 'Experiment'
        },
        location: {
            type: 'string',
            maxLength: 255,
            title: 'Location'
        },
        population: {
            type: 'string',
            maxLength: 255,
            title: 'Population'
        },
        date: {
            type: 'string',
            maxLength: 50,
            title: 'Date'
        },
        platform: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Platform'
        },
        sensor: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sensor'
        },
        storage_path: {
            type: 'string',
            maxLength: 1000,
            title: 'Storage Path'
        }
    },
    type: 'object',
    required: ['data_type', 'experiment', 'location', 'population', 'date', 'storage_path'],
    title: 'FileUploadCreate'
} as const;

export const FileUploadPublicSchema = {
    properties: {
        data_type: {
            type: 'string',
            maxLength: 100,
            title: 'Data Type'
        },
        experiment: {
            type: 'string',
            maxLength: 255,
            title: 'Experiment'
        },
        location: {
            type: 'string',
            maxLength: 255,
            title: 'Location'
        },
        population: {
            type: 'string',
            maxLength: 255,
            title: 'Population'
        },
        date: {
            type: 'string',
            maxLength: 50,
            title: 'Date'
        },
        platform: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Platform'
        },
        sensor: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sensor'
        },
        storage_path: {
            type: 'string',
            maxLength: 1000,
            title: 'Storage Path'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        original_filename: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Original Filename'
        },
        file_count: {
            type: 'integer',
            title: 'File Count'
        },
        file_size_bytes: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Size Bytes'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['data_type', 'experiment', 'location', 'population', 'date', 'storage_path', 'id', 'owner_id', 'original_filename', 'file_count', 'file_size_bytes', 'status', 'notes', 'created_at'],
    title: 'FileUploadPublic'
} as const;

export const FileUploadUpdateSchema = {
    properties: {
        data_type: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data Type'
        },
        experiment: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experiment'
        },
        location: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        population: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Population'
        },
        date: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        platform: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Platform'
        },
        sensor: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sensor'
        },
        storage_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storage Path'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        file_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Count'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'FileUploadUpdate'
} as const;

export const FileUploadsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FileUploadPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FileUploadsPublic'
} as const;

export const GcpSelectionRequestSchema = {
    properties: {
        gcp_selections: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Gcp Selections'
        },
        image_gps: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Image Gps'
        },
        gcp_locations_csv: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gcp Locations Csv'
        }
    },
    type: 'object',
    required: ['gcp_selections', 'image_gps'],
    title: 'GcpSelectionRequest'
} as const;

export const GeneratePlotGridRequestSchema = {
    properties: {
        pop_boundary: {
            additionalProperties: true,
            type: 'object',
            title: 'Pop Boundary'
        },
        options: {
            additionalProperties: true,
            type: 'object',
            title: 'Options'
        }
    },
    type: 'object',
    required: ['pop_boundary', 'options'],
    title: 'GeneratePlotGridRequest'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const LocalCopyRequestSchema = {
    properties: {
        file_paths: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'File Paths'
        },
        data_type: {
            type: 'string',
            title: 'Data Type'
        },
        target_root_dir: {
            type: 'string',
            title: 'Target Root Dir'
        },
        reupload: {
            type: 'boolean',
            title: 'Reupload',
            default: false
        },
        experiment: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experiment'
        },
        location: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Location'
        },
        population: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Population'
        },
        date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date'
        },
        platform: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Platform'
        },
        sensor: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sensor'
        }
    },
    type: 'object',
    required: ['file_paths', 'data_type', 'target_root_dir'],
    title: 'LocalCopyRequest'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModelConfigSchema = {
    properties: {
        label: {
            type: 'string',
            title: 'Label'
        },
        roboflow_api_key: {
            type: 'string',
            title: 'Roboflow Api Key'
        },
        roboflow_model_id: {
            type: 'string',
            title: 'Roboflow Model Id'
        },
        task_type: {
            type: 'string',
            title: 'Task Type',
            default: 'detection'
        }
    },
    type: 'object',
    required: ['label', 'roboflow_api_key', 'roboflow_model_id'],
    title: 'ModelConfig'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PipelineCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        type: {
            type: 'string',
            maxLength: 50,
            title: 'Type'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        }
    },
    type: 'object',
    required: ['name', 'type', 'workspace_id'],
    title: 'PipelineCreate'
} as const;

export const PipelinePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        type: {
            type: 'string',
            maxLength: 50,
            title: 'Type'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspace_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workspace Id'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'type', 'id', 'workspace_id', 'created_at', 'updated_at'],
    title: 'PipelinePublic'
} as const;

export const PipelineRunCreateSchema = {
    properties: {
        date: {
            type: 'string',
            maxLength: 50,
            title: 'Date'
        },
        experiment: {
            type: 'string',
            maxLength: 255,
            title: 'Experiment'
        },
        location: {
            type: 'string',
            maxLength: 255,
            title: 'Location'
        },
        population: {
            type: 'string',
            maxLength: 255,
            title: 'Population'
        },
        platform: {
            type: 'string',
            maxLength: 255,
            title: 'Platform'
        },
        sensor: {
            type: 'string',
            maxLength: 255,
            title: 'Sensor'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        current_step: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Step'
        },
        steps_completed: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'boolean'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Steps Completed'
        },
        outputs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Outputs'
        },
        error: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        pipeline_id: {
            type: 'string',
            format: 'uuid',
            title: 'Pipeline Id'
        },
        file_upload_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Upload Id'
        }
    },
    type: 'object',
    required: ['date', 'experiment', 'location', 'population', 'platform', 'sensor', 'pipeline_id'],
    title: 'PipelineRunCreate'
} as const;

export const PipelineRunPublicSchema = {
    properties: {
        date: {
            type: 'string',
            maxLength: 50,
            title: 'Date'
        },
        experiment: {
            type: 'string',
            maxLength: 255,
            title: 'Experiment'
        },
        location: {
            type: 'string',
            maxLength: 255,
            title: 'Location'
        },
        population: {
            type: 'string',
            maxLength: 255,
            title: 'Population'
        },
        platform: {
            type: 'string',
            maxLength: 255,
            title: 'Platform'
        },
        sensor: {
            type: 'string',
            maxLength: 255,
            title: 'Sensor'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        current_step: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Step'
        },
        steps_completed: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'boolean'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Steps Completed'
        },
        outputs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Outputs'
        },
        error: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        pipeline_id: {
            type: 'string',
            format: 'uuid',
            title: 'Pipeline Id'
        },
        file_upload_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'File Upload Id'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['date', 'experiment', 'location', 'population', 'platform', 'sensor', 'id', 'pipeline_id', 'file_upload_id', 'created_at', 'completed_at'],
    title: 'PipelineRunPublic'
} as const;

export const PipelineRunUpdateSchema = {
    properties: {
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        current_step: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Step'
        },
        steps_completed: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'boolean'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Steps Completed'
        },
        outputs: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Outputs'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    title: 'PipelineRunUpdate'
} as const;

export const PipelineRunsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PipelineRunPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PipelineRunsPublic'
} as const;

export const PipelineUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        config: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Config'
        }
    },
    type: 'object',
    title: 'PipelineUpdate'
} as const;

export const PipelinesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PipelinePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PipelinesPublic'
} as const;

export const PlotBoundariesRequestSchema = {
    properties: {
        geojson: {
            additionalProperties: true,
            type: 'object',
            title: 'Geojson'
        },
        version: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Version'
        }
    },
    type: 'object',
    required: ['geojson'],
    title: 'PlotBoundariesRequest'
} as const;

export const PlotMarkingRequestSchema = {
    properties: {
        selections: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Selections'
        }
    },
    type: 'object',
    required: ['selections'],
    title: 'PlotMarkingRequest'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RenameOrthoRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RenameOrthoRequest'
} as const;

export const RenamePlotBoundaryRequestSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'RenamePlotBoundaryRequest'
} as const;

export const SaveFieldDesignRequestSchema = {
    properties: {
        csv_text: {
            type: 'string',
            title: 'Csv Text'
        }
    },
    type: 'object',
    required: ['csv_text'],
    title: 'SaveFieldDesignRequest'
} as const;

export const SaveGcpLocationsRequestSchema = {
    properties: {
        csv_text: {
            type: 'string',
            title: 'Csv Text'
        }
    },
    type: 'object',
    required: ['csv_text'],
    title: 'SaveGcpLocationsRequest'
} as const;

export const SavePlotGridRequestSchema = {
    properties: {
        geojson: {
            additionalProperties: true,
            type: 'object',
            title: 'Geojson'
        },
        pop_boundary: {
            additionalProperties: true,
            type: 'object',
            title: 'Pop Boundary'
        },
        grid_options: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grid Options'
        },
        grid_offset: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grid Offset'
        },
        ortho_version: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ortho Version'
        },
        save_as: {
            type: 'boolean',
            title: 'Save As',
            default: false
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    required: ['geojson', 'pop_boundary'],
    title: 'SavePlotGridRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkspaceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'WorkspaceCreate'
} as const;

export const WorkspacePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'owner_id', 'created_at'],
    title: 'WorkspacePublic'
} as const;

export const WorkspaceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'WorkspaceUpdate'
} as const;

export const WorkspacesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/WorkspacePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'WorkspacesPublic'
} as const;