// This file is auto-generated by @hey-api/openapi-ts

export type _UseUploadedOrthoRequest = {
    file_upload_id?: (string | null);
    dem_file_upload_id?: (string | null);
    save_mode?: string;
    name?: (string | null);
};

export type ApplyThresholdRequest = {
    confidence_threshold: number;
    label?: (string | null);
};

export type AppSettingPublic = {
    key: string;
    value: string;
};

export type AppSettingUpdate = {
    value: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_reference_data_parse_headers = {
    file: (Blob | File);
};

export type Body_reference_data_upload_reference_data = {
    file: (Blob | File);
};

export type CheckExistingRequest = {
    target_root_dir: string;
    file_names: Array<(string)>;
    data_type?: string;
};

export type ConvertGeoTiffRequest = {
    file_path: string;
};

export type DeleteImagesRequest = {
    paths: Array<(string)>;
};

export type DockerResourcesPublic = {
    cpus?: (number | null);
    memory_gb?: (number | null);
    swap_gb?: (number | null);
};

export type DockerResourcesUpdate = {
    cpus?: (number | null);
    memory_gb?: (number | null);
    swap_gb?: (number | null);
};

export type ExecuteStepRequest = {
    step: string;
    models?: Array<ModelConfig>;
    stitch_name?: (string | null);
    plot_marking_version?: (number | null);
    ortho_name?: (string | null);
    ortho_version?: (number | null);
    boundary_version?: (number | null);
    exg_threshold?: number;
    stitch_version?: (number | null);
    association_version?: (number | null);
    trait_version?: (number | null);
    inference_mode?: string;
    local_server_url?: (string | null);
    sync_mode?: string;
    sync_source_run_id?: (string | null);
    sync_max_extrapolation_sec?: number;
};

export type FileUploadCreate = {
    data_type: string;
    experiment: string;
    location: string;
    population: string;
    date: string;
    platform?: (string | null);
    sensor?: (string | null);
    storage_path: string;
    msgs_synced_path?: (string | null);
};

export type FileUploadPublic = {
    data_type: string;
    experiment: string;
    location: string;
    population: string;
    date: string;
    platform?: (string | null);
    sensor?: (string | null);
    storage_path: string;
    msgs_synced_path: (string | null);
    id: string;
    owner_id: string;
    original_filename: (string | null);
    file_count: number;
    file_size_bytes: (number | null);
    status: string;
    notes: (string | null);
    created_at: string;
};

export type FileUploadsPublic = {
    data: Array<FileUploadPublic>;
    count: number;
};

export type FileUploadUpdate = {
    data_type?: (string | null);
    experiment?: (string | null);
    location?: (string | null);
    population?: (string | null);
    date?: (string | null);
    platform?: (string | null);
    sensor?: (string | null);
    storage_path?: (string | null);
    status?: (string | null);
    file_count?: (number | null);
    notes?: (string | null);
    msgs_synced_path?: (string | null);
};

export type GcpSelectionRequest = {
    gcp_selections: Array<{
        [key: string]: unknown;
    }>;
    image_gps: Array<{
        [key: string]: unknown;
    }>;
    gcp_locations_csv?: (string | null);
};

export type GeneratePlotGridRequest = {
    pop_boundary: {
        [key: string]: unknown;
    };
    options: {
        [key: string]: unknown;
    };
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type LocalCopyRequest = {
    file_paths: Array<(string)>;
    data_type: string;
    target_root_dir: string;
    reupload?: boolean;
    experiment?: (string | null);
    location?: (string | null);
    population?: (string | null);
    date?: (string | null);
    platform?: (string | null);
    sensor?: (string | null);
};

export type MarkStepCompleteBody = {
    step: string;
};

/**
 * Returned after upload or association to show how many plots matched.
 */
export type MatchReport = {
    total: number;
    matched: number;
    unmatched: number;
    unmatched_plots: Array<{
        [key: string]: (string);
    }>;
};

export type Message = {
    message: string;
};

export type ModelConfig = {
    label: string;
    roboflow_api_key: string;
    roboflow_model_id: string;
    task_type?: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PipelineCreate = {
    name: string;
    type: string;
    config?: ({
    [key: string]: unknown;
} | null);
    workspace_id: string;
};

export type PipelinePublic = {
    name: string;
    type: string;
    config?: ({
    [key: string]: unknown;
} | null);
    id: string;
    workspace_id: string;
    created_at: string;
    updated_at: (string | null);
};

export type PipelineRunCreate = {
    date: string;
    experiment: string;
    location: string;
    population: string;
    platform: string;
    sensor: string;
    status?: string;
    current_step?: (string | null);
    steps_completed?: ({
    [key: string]: (boolean);
} | null);
    outputs?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    pipeline_id: string;
    file_upload_id?: (string | null);
};

export type PipelineRunPublic = {
    date: string;
    experiment: string;
    location: string;
    population: string;
    platform: string;
    sensor: string;
    status?: string;
    current_step?: (string | null);
    steps_completed?: ({
    [key: string]: (boolean);
} | null);
    outputs?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    id: string;
    pipeline_id: string;
    file_upload_id: (string | null);
    created_at: string;
    completed_at: (string | null);
};

export type PipelineRunsPublic = {
    data: Array<PipelineRunPublic>;
    count: number;
};

export type PipelineRunUpdate = {
    status?: (string | null);
    current_step?: (string | null);
    steps_completed?: ({
    [key: string]: (boolean);
} | null);
    outputs?: ({
    [key: string]: unknown;
} | null);
    error?: (string | null);
    completed_at?: (string | null);
};

export type PipelinesPublic = {
    data: Array<PipelinePublic>;
    count: number;
};

export type PipelineUpdate = {
    name?: (string | null);
    config?: ({
    [key: string]: unknown;
} | null);
};

export type PlotBoundariesRequest = {
    geojson: {
        [key: string]: unknown;
    };
    version?: (number | null);
};

export type PlotMarkingRequest = {
    selections: Array<{
        [key: string]: unknown;
    }>;
    save_as?: boolean;
    name?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ReferenceDatasetPublic = {
    id: string;
    name: string;
    experiment: string;
    location: string;
    population: string;
    date: string;
    plot_count: number;
    trait_columns: Array<(string)>;
    created_at: string;
};

export type ReferenceDatasetWithMatch = {
    id: string;
    name: string;
    experiment: string;
    location: string;
    population: string;
    date: string;
    plot_count: number;
    trait_columns: Array<(string)>;
    created_at: string;
    match_report?: (MatchReport | null);
};

export type ReferencePlotPublic = {
    id: string;
    dataset_id: string;
    plot_id: string;
    col: (string | null);
    row: (string | null);
    accession: (string | null);
    traits: ({
    [key: string]: unknown;
} | null);
};

export type ReferencePlotsPublic = {
    data: Array<ReferencePlotPublic>;
    count: number;
};

export type RenameOrthoRequest = {
    name: string;
};

export type RenamePlotBoundaryRequest = {
    name: string;
};

export type RenamePlotMarkingRequest = {
    name: string;
};

export type RenameStitchingRequest = {
    name?: (string | null);
};

export type SaveFieldDesignRequest = {
    csv_text: string;
};

export type SaveGcpLocationsRequest = {
    csv_text: string;
};

export type SaveMsgsSyncedRequest = {
    csv_text: string;
    dest_path: string;
};

export type SavePlotGridRequest = {
    geojson: {
        [key: string]: unknown;
    };
    pop_boundary?: ({
    [key: string]: unknown;
} | null);
    grid_options?: ({
    [key: string]: unknown;
} | null);
    grid_offset?: ({
    [key: string]: unknown;
} | null);
    ortho_version?: (number | null);
    stitch_version?: (number | null);
    save_as?: boolean;
    name?: (string | null);
};

export type SystemInfoPublic = {
    cpu_count: number;
    total_ram_gb: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WorkspaceCreate = {
    name: string;
    description?: (string | null);
};

export type WorkspacePublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
};

export type WorkspacesPublic = {
    data: Array<WorkspacePublic>;
    count: number;
};

export type WorkspaceUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type AnalyzeListRunsResponse = (Array<{
    [key: string]: unknown;
}>);

export type AnalyzeGetTraitsData = {
    runId: string;
};

export type AnalyzeGetTraitsResponse = ({
    [key: string]: unknown;
});

export type AnalyzeListTraitRecordsData = {
    pipelineId?: (string | null);
    runId?: (string | null);
    workspaceId?: (string | null);
};

export type AnalyzeListTraitRecordsResponse = (Array<{
    [key: string]: unknown;
}>);

export type AnalyzeGetTraitRecordGeojsonData = {
    recordId: string;
};

export type AnalyzeGetTraitRecordGeojsonResponse = ({
    [key: string]: unknown;
});

export type AnalyzeGetTraitRecordOrthoInfoData = {
    recordId: string;
};

export type AnalyzeGetTraitRecordOrthoInfoResponse = ({
    [key: string]: unknown;
});

export type AnalyzeGetTraitRecordPlotImageData = {
    plotId: string;
    recordId: string;
};

export type AnalyzeGetTraitRecordPlotImageResponse = (unknown);

export type AnalyzeGetTraitRecordImagePlotIdsData = {
    recordId: string;
};

export type AnalyzeGetTraitRecordImagePlotIdsResponse = ({
    [key: string]: unknown;
});

export type AnalyzeDeleteTraitRecordData = {
    recordId: string;
};

export type AnalyzeDeleteTraitRecordResponse = (null);

export type AnalyzeGetOrthoInfoData = {
    runId: string;
};

export type AnalyzeGetOrthoInfoResponse = ({
    [key: string]: unknown;
});

export type AnalyzeListPlotRecordsData = {
    accession?: (string | null);
    col?: (string | null);
    date?: (string | null);
    experiment?: (string | null);
    limit?: number;
    location?: (string | null);
    offset?: number;
    pipelineName?: (string | null);
    pipelineType?: (string | null);
    plotId?: (string | null);
    row?: (string | null);
    workspaceName?: (string | null);
};

export type AnalyzeListPlotRecordsResponse = ({
    [key: string]: unknown;
});

export type AnalyzeGetMasterTableData = {
    workspaceId: string;
};

export type AnalyzeGetMasterTableResponse = ({
    [key: string]: unknown;
});

export type FilesServeFileData = {
    /**
     * Absolute path to the file on disk
     */
    path: string;
};

export type FilesServeFileResponse = (unknown);

export type FilesCreateFileData = {
    requestBody: FileUploadCreate;
};

export type FilesCreateFileResponse = (FileUploadPublic);

export type FilesReadFilesData = {
    limit?: number;
    skip?: number;
};

export type FilesReadFilesResponse = (FileUploadsPublic);

export type FilesReadFieldValuesData = {
    dataType?: (string | null);
    experiment?: (string | null);
    location?: (string | null);
    platform?: (string | null);
    population?: (string | null);
    sensor?: (string | null);
};

export type FilesReadFieldValuesResponse = ({
    [key: string]: Array<(string)>;
});

export type FilesListUploadedOrthosResponse = (Array<{
    [key: string]: unknown;
}>);

export type FilesListUploadedDemsResponse = (Array<{
    [key: string]: unknown;
}>);

export type FilesReadFileData = {
    id: string;
};

export type FilesReadFileResponse = (FileUploadPublic);

export type FilesUpdateFileData = {
    id: string;
    requestBody: FileUploadUpdate;
};

export type FilesUpdateFileResponse = (FileUploadPublic);

export type FilesDeleteFileData = {
    id: string;
};

export type FilesDeleteFileResponse = (Message);

export type FilesDeleteUploadImagesData = {
    id: string;
    requestBody: DeleteImagesRequest;
};

export type FilesDeleteUploadImagesResponse = (unknown);

export type FilesListUploadImagesData = {
    id: string;
};

export type FilesListUploadImagesResponse = (unknown);

export type FilesDownloadUploadZipData = {
    id: string;
};

export type FilesDownloadUploadZipResponse = (unknown);

export type FilesSyncFilesResponse = (unknown);

export type FilesExtractMetadataData = {
    requestBody: {
        [key: string]: (string);
    };
};

export type FilesExtractMetadataResponse = (unknown);

export type FilesCheckGeotiffData = {
    /**
     * Absolute path to the GeoTIFF
     */
    path: string;
};

export type FilesCheckGeotiffResponse = ({
    [key: string]: unknown;
});

export type FilesConvertGeotiffData = {
    requestBody: ConvertGeoTiffRequest;
};

export type FilesConvertGeotiffResponse = ({
    [key: string]: unknown;
});

export type FilesCopyLocalFilesData = {
    requestBody: LocalCopyRequest;
};

export type FilesCopyLocalFilesResponse = (unknown);

export type FilesSaveMsgsSyncedData = {
    requestBody: SaveMsgsSyncedRequest;
};

export type FilesSaveMsgsSyncedResponse = ({
    [key: string]: unknown;
});

export type FilesCheckExistingFilesData = {
    requestBody: CheckExistingRequest;
};

export type FilesCheckExistingFilesResponse = ({
    [key: string]: Array<(string)>;
});

export type FilesCopyLocalFilesStreamData = {
    requestBody: LocalCopyRequest;
};

export type FilesCopyLocalFilesStreamResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PipelinesCreateData = {
    requestBody: PipelineCreate;
    workspaceId: string;
};

export type PipelinesCreateResponse = (PipelinePublic);

export type PipelinesReadAllData = {
    limit?: number;
    skip?: number;
    workspaceId: string;
};

export type PipelinesReadAllResponse = (PipelinesPublic);

export type PipelinesReadOneData = {
    id: string;
};

export type PipelinesReadOneResponse = (PipelinePublic);

export type PipelinesUpdateData = {
    id: string;
    requestBody: PipelineUpdate;
};

export type PipelinesUpdateResponse = (PipelinePublic);

export type PipelinesDeleteData = {
    id: string;
};

export type PipelinesDeleteResponse = (Message);

export type PipelinesCreateRunData = {
    pipelineId: string;
    requestBody: PipelineRunCreate;
};

export type PipelinesCreateRunResponse = (PipelineRunPublic);

export type PipelinesReadRunsData = {
    limit?: number;
    pipelineId: string;
    skip?: number;
};

export type PipelinesReadRunsResponse = (PipelineRunsPublic);

export type PipelinesReadRunData = {
    id: string;
};

export type PipelinesReadRunResponse = (PipelineRunPublic);

export type PipelinesUpdateRunData = {
    id: string;
    requestBody: PipelineRunUpdate;
};

export type PipelinesUpdateRunResponse = (PipelineRunPublic);

export type PipelinesDeleteRunData = {
    id: string;
};

export type PipelinesDeleteRunResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProcessingAvailableSyncSourcesData = {
    id: string;
};

export type ProcessingAvailableSyncSourcesResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProcessingExecuteStepData = {
    id: string;
    requestBody: ExecuteStepRequest;
};

export type ProcessingExecuteStepResponse = ({
    [key: string]: (string);
});

export type ProcessingStopStepData = {
    id: string;
};

export type ProcessingStopStepResponse = ({
    [key: string]: (string);
});

export type ProcessingProgressStreamData = {
    id: string;
    offset?: number;
};

export type ProcessingProgressStreamResponse = (unknown);

export type ProcessingListOutputsData = {
    id: string;
};

export type ProcessingListOutputsResponse = ({
    [key: string]: unknown;
});

export type ProcessingListPlotMarkingsData = {
    id: string;
};

export type ProcessingListPlotMarkingsResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProcessingSavePlotMarkingData = {
    id: string;
    requestBody: PlotMarkingRequest;
};

export type ProcessingSavePlotMarkingResponse = ({
    [key: string]: unknown;
});

export type ProcessingLoadPlotMarkingData = {
    id: string;
    version?: (number | null);
};

export type ProcessingLoadPlotMarkingResponse = ({
    [key: string]: unknown;
});

export type ProcessingRenamePlotMarkingData = {
    id: string;
    requestBody: RenamePlotMarkingRequest;
    version: number;
};

export type ProcessingRenamePlotMarkingResponse = ({
    [key: string]: unknown;
});

export type ProcessingDeletePlotMarkingVersionData = {
    id: string;
    version: number;
};

export type ProcessingDeletePlotMarkingVersionResponse = (null);

export type ProcessingListImagesData = {
    extensions?: string;
    id: string;
};

export type ProcessingListImagesResponse = ({
    [key: string]: unknown;
});

export type ProcessingGetGpsDataData = {
    id: string;
};

export type ProcessingGetGpsDataResponse = ({
    [key: string]: unknown;
});

export type ProcessingApplyBoundariesData = {
    id: string;
};

export type ProcessingApplyBoundariesResponse = ({
    [key: string]: unknown;
});

export type ProcessingGetFieldDesignData = {
    id: string;
};

export type ProcessingGetFieldDesignResponse = ({
    [key: string]: unknown;
});

export type ProcessingSaveFieldDesignData = {
    id: string;
    requestBody: SaveFieldDesignRequest;
};

export type ProcessingSaveFieldDesignResponse = ({
    [key: string]: unknown;
});

export type ProcessingSavePlotGridData = {
    id: string;
    requestBody: SavePlotGridRequest;
};

export type ProcessingSavePlotGridResponse = ({
    [key: string]: unknown;
});

export type ProcessingTraitExtractionPreviewData = {
    boundaryVersion?: (number | null);
    id: string;
    orthoVersion?: (number | null);
    plotIndex?: number;
    threshold?: number;
};

export type ProcessingTraitExtractionPreviewResponse = ({
    [key: string]: unknown;
});

export type ProcessingGeneratePlotGridData = {
    id: string;
    requestBody: GeneratePlotGridRequest;
};

export type ProcessingGeneratePlotGridResponse = ({
    [key: string]: unknown;
});

export type ProcessingSaveGcpSelectionData = {
    id: string;
    requestBody: GcpSelectionRequest;
};

export type ProcessingSaveGcpSelectionResponse = ({
    [key: string]: unknown;
});

export type ProcessingGcpCandidatesData = {
    filterByGcp?: boolean;
    id: string;
    radiusM?: number;
};

export type ProcessingGcpCandidatesResponse = ({
    [key: string]: unknown;
});

export type ProcessingSaveGcpLocationsData = {
    id: string;
    requestBody: SaveGcpLocationsRequest;
};

export type ProcessingSaveGcpLocationsResponse = ({
    [key: string]: unknown;
});

export type ProcessingSavePlotBoundariesData = {
    id: string;
    requestBody: PlotBoundariesRequest;
};

export type ProcessingSavePlotBoundariesResponse = ({
    [key: string]: unknown;
});

export type ProcessingListPlotBoundariesData = {
    id: string;
};

export type ProcessingListPlotBoundariesResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProcessingOrthomosaicInfoData = {
    id: string;
};

export type ProcessingOrthomosaicInfoResponse = ({
    [key: string]: unknown;
});

export type ProcessingAutoBoundaryData = {
    id: string;
};

export type ProcessingAutoBoundaryResponse = ({
    [key: string]: unknown;
});

export type ProcessingGetPlotBoundaryVersionData = {
    id: string;
    version: number;
};

export type ProcessingGetPlotBoundaryVersionResponse = ({
    [key: string]: unknown;
});

export type ProcessingDeletePlotBoundaryData = {
    id: string;
    version: number;
};

export type ProcessingDeletePlotBoundaryResponse = (null);

export type ProcessingMosaicPreviewData = {
    id: string;
    maxSize?: number;
    stitchVersion?: (number | null);
};

export type ProcessingMosaicPreviewResponse = (unknown);

export type ProcessingListOrthomosaicsData = {
    id: string;
};

export type ProcessingListOrthomosaicsResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProcessingOrthomosaicVersionPreviewData = {
    id: string;
    maxSize?: number;
    version: number;
};

export type ProcessingOrthomosaicVersionPreviewResponse = (unknown);

export type ProcessingDeleteOrthomosaicData = {
    id: string;
    version: number;
};

export type ProcessingDeleteOrthomosaicResponse = (null);

export type ProcessingActivateOrthomosaicData = {
    id: string;
    version: number;
};

export type ProcessingActivateOrthomosaicResponse = ({
    [key: string]: unknown;
});

export type ProcessingRenameOrthomosaicData = {
    id: string;
    requestBody: RenameOrthoRequest;
    version: number;
};

export type ProcessingRenameOrthomosaicResponse = ({
    [key: string]: unknown;
});

export type ProcessingRenamePlotBoundaryData = {
    id: string;
    requestBody: RenamePlotBoundaryRequest;
    version: number;
};

export type ProcessingRenamePlotBoundaryResponse = ({
    [key: string]: unknown;
});

export type ProcessingDownloadCropsForBoundaryData = {
    boundaryVersion: number;
    id: string;
    orthoVersion: number;
};

export type ProcessingDownloadCropsForBoundaryResponse = (unknown);

export type ProcessingUseUploadedOrthoData = {
    id: string;
    requestBody?: (_UseUploadedOrthoRequest | null);
};

export type ProcessingUseUploadedOrthoResponse = ({
    [key: string]: unknown;
});

export type ProcessingCheckUploadedOrthoData = {
    id: string;
};

export type ProcessingCheckUploadedOrthoResponse = ({
    [key: string]: unknown;
});

export type ProcessingInferenceResultsData = {
    id: string;
    model?: (string | null);
};

export type ProcessingInferenceResultsResponse = ({
    [key: string]: unknown;
});

export type ProcessingMarkStepCompleteData = {
    id: string;
    requestBody: MarkStepCompleteBody;
};

export type ProcessingMarkStepCompleteResponse = ({
    [key: string]: unknown;
});

export type ProcessingApplyInferenceThresholdData = {
    id: string;
    requestBody: ApplyThresholdRequest;
};

export type ProcessingApplyInferenceThresholdResponse = ({
    [key: string]: unknown;
});

export type ProcessingListStitchingsData = {
    id: string;
};

export type ProcessingListStitchingsResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProcessingDownloadStitchingImagesData = {
    associationVersion?: (number | null);
    id: string;
    version: number;
};

export type ProcessingDownloadStitchingImagesResponse = (unknown);

export type ProcessingRenameStitchingData = {
    id: string;
    requestBody: RenameStitchingRequest;
    version: number;
};

export type ProcessingRenameStitchingResponse = ({
    [key: string]: unknown;
});

export type ProcessingDeleteStitchingData = {
    id: string;
    version: number;
};

export type ProcessingDeleteStitchingResponse = ({
    [key: string]: unknown;
});

export type ProcessingListAssociationsData = {
    id: string;
};

export type ProcessingListAssociationsResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProcessingDeleteAssociationData = {
    id: string;
    version: number;
};

export type ProcessingDeleteAssociationResponse = ({
    [key: string]: unknown;
});

export type ProcessingGetStitchOutputsData = {
    id: string;
    version?: (number | null);
};

export type ProcessingGetStitchOutputsResponse = ({
    [key: string]: unknown;
});

export type ProcessingGetInferenceResultsData = {
    id: string;
};

export type ProcessingGetInferenceResultsResponse = (Array<{
    [key: string]: unknown;
}>);

export type ProcessingDeleteInferenceResultData = {
    id: string;
    label: string;
};

export type ProcessingDeleteInferenceResultResponse = ({
    [key: string]: unknown;
});

export type ProcessingDownloadCropsData = {
    id: string;
    orthoVersion?: (number | null);
};

export type ProcessingDownloadCropsResponse = (unknown);

export type ProcessingMigratePlotBoundariesResponse = ({
    [key: string]: unknown;
});

export type ReferenceDataParseHeadersData = {
    formData: Body_reference_data_parse_headers;
};

export type ReferenceDataParseHeadersResponse = ({
    [key: string]: Array<(string)>;
});

export type ReferenceDataUploadReferenceDataData = {
    /**
     * JSON string: { original_col: canonical_name }
     */
    columnMappingJson: string;
    date?: string;
    experiment?: string;
    formData: Body_reference_data_upload_reference_data;
    location?: string;
    /**
     * Required dataset name
     */
    name: string;
    population?: string;
};

export type ReferenceDataUploadReferenceDataResponse = (ReferenceDatasetWithMatch);

export type ReferenceDataListDatasetsData = {
    experiment?: (string | null);
    location?: (string | null);
    population?: (string | null);
};

export type ReferenceDataListDatasetsResponse = (Array<ReferenceDatasetPublic>);

export type ReferenceDataGetDatasetData = {
    datasetId: string;
};

export type ReferenceDataGetDatasetResponse = (ReferenceDatasetPublic);

export type ReferenceDataDeleteDatasetData = {
    datasetId: string;
};

export type ReferenceDataDeleteDatasetResponse = ({
    [key: string]: (string);
});

export type ReferenceDataListPlotsData = {
    datasetId: string;
    limit?: number;
    skip?: number;
};

export type ReferenceDataListPlotsResponse = (ReferencePlotsPublic);

export type ReferenceDataListWorkspaceDatasetsData = {
    workspaceId: string;
};

export type ReferenceDataListWorkspaceDatasetsResponse = (Array<ReferenceDatasetWithMatch>);

export type ReferenceDataAssociateDatasetData = {
    datasetId: string;
    workspaceId: string;
};

export type ReferenceDataAssociateDatasetResponse = (ReferenceDatasetWithMatch);

export type ReferenceDataRemoveDatasetFromWorkspaceData = {
    datasetId: string;
    workspaceId: string;
};

export type ReferenceDataRemoveDatasetFromWorkspaceResponse = ({
    [key: string]: (string);
});

export type ReferenceDataMatchPlotData = {
    col?: (string | null);
    experiment: string;
    location: string;
    plotId: string;
    population: string;
    row?: (string | null);
    workspaceId: string;
};

export type ReferenceDataMatchPlotResponse = (unknown);

export type SettingsReadDataRootResponse = (AppSettingPublic);

export type SettingsUpdateDataRootData = {
    requestBody: AppSettingUpdate;
};

export type SettingsUpdateDataRootResponse = (AppSettingPublic);

export type SettingsReadSystemInfoResponse = (SystemInfoPublic);

export type SettingsReadDockerResourcesResponse = (DockerResourcesPublic);

export type SettingsUpdateDockerResourcesData = {
    requestBody: DockerResourcesUpdate;
};

export type SettingsUpdateDockerResourcesResponse = (DockerResourcesPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsGetLogsResponse = (Array<{
    [key: string]: unknown;
}>);

export type UtilsDockerCheckResponse = ({
    [key: string]: unknown;
});

export type UtilsCapabilitiesResponse = ({
    [key: string]: unknown;
});

export type WorkspacesCreateData = {
    requestBody: WorkspaceCreate;
};

export type WorkspacesCreateResponse = (WorkspacePublic);

export type WorkspacesReadAllData = {
    limit?: number;
    skip?: number;
};

export type WorkspacesReadAllResponse = (WorkspacesPublic);

export type WorkspacesSyncWorkspacesResponse = ({
    [key: string]: unknown;
});

export type WorkspacesWorkspaceStatsResponse = ({
    [key: string]: unknown;
});

export type WorkspacesReadOneData = {
    id: string;
};

export type WorkspacesReadOneResponse = (WorkspacePublic);

export type WorkspacesUpdateData = {
    id: string;
    requestBody: WorkspaceUpdate;
};

export type WorkspacesUpdateResponse = (WorkspacePublic);

export type WorkspacesDeleteData = {
    id: string;
};

export type WorkspacesDeleteResponse = (Message);

export type WorkspacesWorkspaceCardImagesData = {
    id: string;
};

export type WorkspacesWorkspaceCardImagesResponse = (Array<{
    [key: string]: unknown;
}>);