version: '3.8'
services:
  service-1:
    image: gemini_train:v0.3
    user: "${UID:-1000}:${GID:-1000}"
    container_name: train
    volumes:
      - /home/gemini/data/GEMINI-Data:/app/mnt
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all  # Use all available GPUs
            capabilities: [gpu]
    ipc: host  # Set ipc mode to host
    command: ["tail", "-f", "/dev/null"]

  service-2:
    image: gemini_opcuda_86:v1.1
    user: "${UID:-1000}:${GID:-1000}"
    container_name: locate-extract
    volumes:
      - /home/gemini/data/GEMINI-Data:/app/mnt
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all  # Use all available GPUs
            capabilities: [gpu]
    ipc: host  # Set ipc mode to host
    command: ["tail", "-f", "/dev/null"]