version: '3.8'
services:
  service-1:
    image: gemini_train:v0.5
    user: "${UID:-1000}:${GID:-1000}"
    container_name: train
    volumes:
      - /home/gemini/data/GEMINI-App-Data:/app/mnt
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all  # Use all available GPUs
            capabilities: [gpu]
    ipc: host  # Set ipc mode to host
    command: ["tail", "-f", "/dev/null"]

  service-2:
    image: gemini_opcuda_86:v2.53
    container_name: locate-extract
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - /home/gemini/data/GEMINI-App-Data:/app/mnt
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all  # Use all available GPUs
            capabilities: [gpu]
    ipc: host  # Set ipc mode to host
    stdin_open: true  # Keeps stdin open
    tty: true         # Allocates a pseudo-TTY, making the container's bash session interactive
    command: >
      /bin/sh -c "
        . /miniconda/etc/profile.d/conda.sh &&
        conda activate env &&
        conda info &&
        tail -f /dev/null
      "