/**
 * Round-trip tests for the spreadsheet parser.
 *
 * The xlsx code path uses SheetJS which has its own test suite — we don't
 * re-test it. We do exercise the CSV / TSV branches and the multi-sheet
 * xlsx case so any future change to the wrapper (banner-row detection,
 * trailing-empty-column trim, delimiter detection) is caught.
 */

import { describe, expect, it } from "vitest"

import {
  autoDetectCsvSkipRows,
  detectSkipRows,
  findHeaderRowIndex,
  parseSpreadsheet,
  readFirstNLines,
} from "./spreadsheet"

function csvFile(text: string, name = "test.csv"): File {
  return new File([text], name, { type: "text/csv" })
}

describe("parseSpreadsheet", () => {
  it("parses a simple CSV", async () => {
    const f = csvFile(
      ["plot_number,plant_height_cm,yield_kg", "1,142,4.2", "2,150,4.5"].join(
        "\n",
      ),
    )
    const sheets = await parseSpreadsheet(f)
    expect(sheets).toHaveLength(1)
    expect(sheets[0].headers).toEqual([
      "plot_number",
      "plant_height_cm",
      "yield_kg",
    ])
    expect(sheets[0].rows).toHaveLength(2)
    expect(sheets[0].rows[0]).toEqual({
      plot_number: "1",
      plant_height_cm: "142",
      yield_kg: "4.2",
    })
  })

  it("parses a TSV via the .tsv extension", async () => {
    const f = new File(
      [["plot_number\ttrait", "1\t5", "2\t6"].join("\n")],
      "traits.tsv",
      { type: "text/tab-separated-values" },
    )
    const sheets = await parseSpreadsheet(f)
    expect(sheets[0].headers).toEqual(["plot_number", "trait"])
    expect(sheets[0].rows).toHaveLength(2)
    expect(sheets[0].rows[1]).toEqual({ plot_number: "2", trait: "6" })
  })

  it("auto-detects tab delimiter on a .txt with tab-separated header", async () => {
    const f = new File([["a\tb\tc", "1\t2\t3"].join("\n")], "data.txt", {
      type: "text/plain",
    })
    const sheets = await parseSpreadsheet(f)
    expect(sheets[0].headers).toEqual(["a", "b", "c"])
    expect(sheets[0].rows[0]).toEqual({ a: "1", b: "2", c: "3" })
  })

  // XLSX round-trip is upstream-tested by SheetJS itself, and reading
  // an in-memory xlsx through Vitest's jsdom + Node-File polyfill stack
  // doesn't reflect production behaviour (vitest's xlsx import resolves
  // to a path that loses sheets on the round trip even though pure Node
  // and real browsers handle it fine). We exercise xlsx end-to-end via
  // the live-stack Playwright spec in 9e (drops a real .xlsx into the
  // wizard's UploadZone) — that's the contract worth pinning.

  it("auto-skips a banner row in a CSV (≥4-populated-cells heuristic)", async () => {
    // Banner row has 1 populated cell; row 2 is the real header with 4.
    const csv = [
      "Project notes,,,",
      "plot,a,b,c",
      "1,5,6,7",
      "2,8,9,10",
    ].join("\n")
    const f = new File([csv], "banner.csv", { type: "text/csv" })
    const sheets = await parseSpreadsheet(f)
    expect(sheets[0].headers).toEqual(["plot", "a", "b", "c"])
    expect(sheets[0].rows).toHaveLength(2)
    expect(sheets[0].rows[0]).toEqual({ plot: "1", a: "5", b: "6", c: "7" })
  })

  it("explicit skipRows overrides auto-detect", async () => {
    // Two banner rows; user passes skipRows: 2 → row 3 is header.
    const csv = [
      "GEMINI export — May 2026",
      "Generated by tool foo v1.2.3",
      "plot,a,b,c",
      "1,5,6,7",
    ].join("\n")
    const f = new File([csv], "two-banners.csv", { type: "text/csv" })
    const sheets = await parseSpreadsheet(f, { skipRows: 2 })
    expect(sheets[0].headers).toEqual(["plot", "a", "b", "c"])
    expect(sheets[0].rows).toEqual([{ plot: "1", a: "5", b: "6", c: "7" }])
  })

  it("skipRows: 0 disables the auto-detect even if a banner is present", async () => {
    const csv = [
      "Project notes,,,",
      "plot,a,b,c",
      "1,5,6,7",
    ].join("\n")
    const f = new File([csv], "banner.csv", { type: "text/csv" })
    const sheets = await parseSpreadsheet(f, { skipRows: 0 })
    // With explicit skipRows: 0, the banner row becomes the header.
    expect(sheets[0].headers[0]).toBe("Project notes")
  })

  it("skipRows works on TSV", async () => {
    const text = [
      "junk\theader\trow",
      "plot\ta\tb\tc",
      "1\t5\t6\t7",
    ].join("\n")
    const f = new File([text], "data.tsv", {
      type: "text/tab-separated-values",
    })
    const sheets = await parseSpreadsheet(f, { skipRows: 1 })
    expect(sheets[0].headers).toEqual(["plot", "a", "b", "c"])
    expect(sheets[0].rows[0]).toEqual({ plot: "1", a: "5", b: "6", c: "7" })
  })

  it("clamps skipRows when it exceeds available lines", async () => {
    const csv = ["plot,a,b,c", "1,5,6,7"].join("\n")
    const f = new File([csv], "small.csv", { type: "text/csv" })
    // skipRows=10 against a 2-line file — clamp to the last available line
    // so we still emit at least a (possibly empty) sheet rather than
    // throwing.
    const sheets = await parseSpreadsheet(f, { skipRows: 10 })
    expect(sheets).toHaveLength(1)
  })
})

describe("findHeaderRowIndex", () => {
  it("returns 0 when the first row already looks like a header", () => {
    expect(
      findHeaderRowIndex([
        ["plot", "a", "b", "c"],
        ["1", "5", "6", "7"],
      ]),
    ).toBe(0)
  })

  it("skips banner rows with <4 populated cells", () => {
    expect(
      findHeaderRowIndex([
        ["banner", "", "", ""],
        ["another note", "", "", ""],
        ["plot", "a", "b", "c"],
        ["1", "5", "6", "7"],
      ]),
    ).toBe(2)
  })
})

describe("autoDetectCsvSkipRows", () => {
  it("returns 0 when the first row has ≥4 populated cells", () => {
    const csv = ["plot,a,b,c", "1,5,6,7"].join("\n")
    expect(autoDetectCsvSkipRows(csv, ",")).toBe(0)
  })

  it("returns the index of the first row with ≥4 populated cells", () => {
    const csv = ["note,,,", ",,,", "plot,a,b,c", "1,5,6,7"].join("\n")
    expect(autoDetectCsvSkipRows(csv, ",")).toBe(2)
  })

  it("works for tabs", () => {
    const tsv = ["note", "plot\ta\tb\tc", "1\t5\t6\t7"].join("\n")
    expect(autoDetectCsvSkipRows(tsv, "\t")).toBe(1)
  })
})

describe("detectSkipRows", () => {
  it("auto-detects banner rows in a CSV", async () => {
    const f = csvFile(
      ["note,,,", "plot,a,b,c", "1,5,6,7"].join("\n"),
      "banner.csv",
    )
    expect(await detectSkipRows(f)).toBe(1)
  })

  it("returns 0 when the CSV has no banner", async () => {
    const f = csvFile(["plot,a,b,c", "1,5,6,7"].join("\n"))
    expect(await detectSkipRows(f)).toBe(0)
  })
})

describe("readFirstNLines", () => {
  it("returns up to N lines from the head of a text file", async () => {
    const f = csvFile(["a", "b", "c", "d", "e"].join("\n"))
    const lines = await readFirstNLines(f, 3)
    expect(lines).toEqual(["a", "b", "c"])
  })
})
