const { test, expect } = require("@playwright/test");
const {
    cleanupMinIOPrefix,
    deleteExperiment,
    getExperimentByName,
    cancelJob,
    deleteJob,
    getJobsByType,
    listFilesInMinIO,
    API_BASE,
} = require("./helpers/api-helpers");
const {
    seedExperimentEntities,
    selectAutocompleteOption,
} = require("./helpers/prep-helpers");
const { seedFileToMinIO, seedTestOrtho } = require("./helpers/manage-helpers");
const path = require("path");
const fs = require("fs");

/**
 * REAL end-to-end test for the "Associate Plots" workflow.
 *
 * Drives the actual UI — clicking buttons, filling forms, uploading
 * files — exactly as a user would. NO mocking.
 *
 * Full workflow:
 *   1. Navigate to Associate Plots via sidebar
 *   2. Select experiment/year/location/population, begin data preparation
 *   3. Import field design CSV via DataImporter (Step 0)
 *   4. Verify population boundary on BoundaryMap, proceed (Step 1)
 *   5. Verify plot boundaries on BoundaryMap, proceed (Step 2)
 *   6. Split orthomosaic into plot images via PlotImageExtractor (Step 3)
 *   7. Verify plot images in MinIO
 *
 * Prerequisites seeded via API (not the operation under test):
 *   - Experiment entities
 *   - Orthophoto in Processed/ path (simulates prior ODM output)
 *   - Population and plot boundary GeoJSON files
 */

const TEST_RUN_ID = `E2E-PLOTS-${Date.now()}`;

const FIELDS = {
    year: "2022",
    experiment: TEST_RUN_ID,
    location: "Davis",
    population: "Cowpea",
    date: "2022-06-27",
    platform: "DJI",
    sensor: "FC6310S",
};

const PROCESSED_PREFIX = `Processed/${FIELDS.year}/${FIELDS.experiment}/${FIELDS.location}/${FIELDS.population}`;
const INTERMEDIATE_PREFIX = `Intermediate/${FIELDS.year}/${FIELDS.experiment}/${FIELDS.location}/${FIELDS.population}`;
const POP_LEVEL_PREFIX = `${FIELDS.year}/${FIELDS.experiment}/${FIELDS.location}/${FIELDS.population}`;
const PLOT_IMAGES_DIR = `${PROCESSED_PREFIX}/${FIELDS.date}/${FIELDS.platform}/${FIELDS.sensor}/PlotImages`;

// Fixture paths
const ORTHO_FIXTURE = path.join(__dirname, "fixtures", "ortho", "e2e_test_orthophoto.tif");
const PLOT_BOUNDARY_FIXTURE = path.join(__dirname, "fixtures", "geojson", "e2e-plot-boundaries.geojson");
const POP_BOUNDARY_FIXTURE = path.join(__dirname, "fixtures", "geojson", "e2e-pop-boundary.geojson");
const FIELD_DESIGN_FIXTURE = path.join(__dirname, "fixtures", "csv", "e2e-field-design.csv");

let createdJobIds = [];

// Errors to ignore in console/network
const IGNORED_PATTERNS = [
    "chrome-extension", "inject.js", "Source Map", ".map",
    "ERR_BLOCKED_BY_CLIENT", "gemini-breeding.github.io",
    "fonts.gstatic.com", "fonts.googleapis.com",
    "mapbox", "favicon.ico", "Failed to load resource",
    "mapbox-gl", "WebGL", "webgl",
    "Could not fetch bounds", "GeoTIFF", "titiler",
    "Failed to fetch", "tile",
    "FieldDesign.csv",
    "cog/info", "cog/tiles", "FILE_PATH",
    "Received NaN",
    "geojson/load", "Failed to load data",
];

function isIgnored(text) {
    return IGNORED_PATTERNS.some(p => text.toLowerCase().includes(p.toLowerCase()));
}

test.describe("Associate Plots: import CSV → verify boundaries → split orthomosaic", () => {

    test.beforeAll(async ({ request }) => {
        // 1. Create experiment entities
        await seedExperimentEntities(request, FIELDS);

        // 2. Upload orthophoto and COG pyramid to Processed/ path (prerequisite: simulates prior ODM output)
        const orthoBuffer = fs.readFileSync(ORTHO_FIXTURE);
        await seedTestOrtho(request, { ...FIELDS, fileName: "odm_orthophoto.tif" }, orthoBuffer);
        // Seed the COG pyramid so MapOrthoSwitcher can find and overlay the orthophoto
        await seedTestOrtho(request, { ...FIELDS, fileName: "odm_orthophoto-Pyramid.tif" }, orthoBuffer);

        // 3. Save population boundary GeoJSON to MinIO
        const popBoundary = fs.readFileSync(POP_BOUNDARY_FIXTURE, "utf-8");
        await request.post(`${API_BASE}/geojson/save`, {
            data: {
                file_path: `${POP_LEVEL_PREFIX}/Pop-Boundary-WGS84.geojson`,
                geojson: JSON.parse(popBoundary),
            },
        });

        // Plot boundaries are NOT seeded — they are auto-generated by the
        // PlotProposalSwitcher from the field design CSV + ImportSettingsModal dimensions
    });

    test.afterAll(async ({ request }) => {
        for (const jobId of createdJobIds) {
            await cancelJob(request, jobId).catch(() => {});
            await deleteJob(request, jobId).catch(() => {});
        }
        const jobs = await getJobsByType(request, "SPLIT_ORTHOMOSAIC").catch(() => []);
        for (const job of jobs) {
            const jid = job.id || job.job_id;
            if (jid) {
                await cancelJob(request, jid).catch(() => {});
                await deleteJob(request, jid).catch(() => {});
            }
        }
        await cleanupMinIOPrefix(request, PROCESSED_PREFIX).catch(() => {});
        await cleanupMinIOPrefix(request, INTERMEDIATE_PREFIX).catch(() => {});
        await cleanupMinIOPrefix(request, POP_LEVEL_PREFIX).catch(() => {});

        const exp = await getExperimentByName(request, FIELDS.experiment);
        if (exp) {
            await deleteExperiment(request, exp.id || exp.experiment_id).catch(() => {});
        }
    });

    test("full workflow: navigate, import CSV, verify boundaries, split orthomosaic", async ({ page }, testInfo) => {
        testInfo.setTimeout(600_000); // 10 min

        const errors = [];
        page.on("console", msg => {
            if (msg.type() === "error" && !isIgnored(msg.text())) errors.push(msg.text());
        });
        page.on("response", resp => {
            if (resp.status() >= 400 && resp.status() !== 409) {
                const url = resp.url();
                if (!isIgnored(url) && !url.endsWith("/experiments") && !url.includes("/list_nested"))
                    errors.push(`HTTP ${resp.status()} ${resp.request().method()} ${url}`);
            }
        });

        // ── Navigate to Associate Plots ──────────────────────────────────
        await page.goto("/");
        await page.waitForSelector("#root:not(:empty)", { timeout: 15_000 });

        await page.locator("[aria-label='process']").click();
        await page.locator("[aria-label='plot-association']").waitFor({ state: "visible", timeout: 5_000 });
        await page.locator("[aria-label='plot-association']").click();
        await page.waitForTimeout(1_000);

        // Select experiment → year → location → population
        await selectAutocompleteOption(page, "#experiment-combo-box", FIELDS.experiment);
        await selectAutocompleteOption(page, "#year-combo-box", FIELDS.year);
        await selectAutocompleteOption(page, "#location-combo-box", FIELDS.location);
        await selectAutocompleteOption(page, "#population-combo-box", FIELDS.population);

        await page.locator("button:has-text('Begin Data Preparation')").click();
        await page.waitForTimeout(2_000);

        // Verify PlotBoundaryPrep stepper renders
        await expect(page.locator("text=Import Data").first()).toBeVisible({ timeout: 10_000 });
        await expect(page.locator("text=Population Boundary").first()).toBeVisible({ timeout: 5_000 });
        await expect(page.locator("text=Plot Boundary").first()).toBeVisible({ timeout: 5_000 });
        console.log("✓ Navigated to Associate Plots, stepper visible");

        // ── Step 0: Import field design CSV ──────────────────────────────
        await expect(page.locator("#instructions").or(page.locator("text=Instructions")).first()).toBeVisible({ timeout: 10_000 });

        const fileInput = page.locator("input[type='file']").first();
        await fileInput.setInputFiles(FIELD_DESIGN_FIXTURE);
        await page.waitForTimeout(2_000);

        // File preview → click "Choose columns"
        const chooseColumnsButton = page.locator("button:has-text('Choose columns')");
        await expect(chooseColumnsButton).toBeVisible({ timeout: 10_000 });
        await chooseColumnsButton.click();
        await page.waitForTimeout(2_000);

        // Column mapping → click "Import"
        const importButton = page.locator("button:has-text('Import')");
        await expect(importButton).toBeVisible({ timeout: 10_000 });
        await importButton.click();
        await page.waitForTimeout(3_000);

        // ImportSettingsModal opens — set spacing (plot dimensions auto-calculated from pop boundary)
        await expect(page.locator("text=Field Design Settings")).toBeVisible({ timeout: 15_000 });

        const fillModalField = async (name, value) => {
            const field = page.locator(`input[name='${name}']`);
            await field.click({ clickCount: 3 });
            await field.type(String(value));
        };
        await fillModalField("verticalSpacing", 1);
        await fillModalField("horizontalSpacing", 1);
        await fillModalField("angle", 0);
        // rows and columns are auto-populated from CSV (2 and 2)

        await page.locator("button:has-text('Save Settings')").click();
        await page.waitForTimeout(2_000);
        console.log("✓ Step 0: CSV imported, field dimensions set");

        // ── Step 1: Population Boundary ──────────────────────────────────
        // After saving settings, modal closes and step advances to 1
        const canvas = page.locator("canvas").first();
        await expect(canvas).toBeVisible({ timeout: 15_000 });

        // Verify ModeSwitcher panel (View, Draw, Edit, Translate, Select modes)
        await expect(page.locator("label:has-text('View')").first()).toBeVisible({ timeout: 10_000 });
        await expect(page.locator("label:has-text('Draw')").first()).toBeVisible({ timeout: 5_000 });

        // Verify the MapOrthoSwitcher shows the orthophoto date is available
        // The switcher has a "Select a date" label on an Autocomplete input
        const dateLabel = page.locator("label:has-text('Select a date')");
        await expect(dateLabel).toBeVisible({ timeout: 10_000 });
        // Click the input associated with the label to open the dropdown
        const dateCombobox = dateLabel.locator("..").locator("input");
        await dateCombobox.click();
        await page.waitForTimeout(1_000);
        const dateOption = page.locator(`li[role="option"]:has-text("${FIELDS.date}")`);
        await expect(dateOption).toBeVisible({ timeout: 10_000 });
        await dateOption.click();
        await page.waitForTimeout(2_000);
        console.log("✓ Step 1: Orthophoto overlay date available and selected");

        // Verify Save and Proceed buttons
        const proceedButton = page.locator("button:has-text('Proceed')").first();
        await expect(proceedButton).toBeVisible({ timeout: 5_000 });

        // Proceed to Step 2
        await proceedButton.click();
        await page.waitForTimeout(3_000);
        console.log("✓ Step 1: Population boundary verified, proceeded");

        // ── Step 2: Plot Boundary ────────────────────────────────────────
        // Plot boundaries should be auto-generated from field dimensions + population boundary
        await expect(canvas).toBeVisible({ timeout: 10_000 });
        await expect(page.locator("button:has-text('Select All')").first()).toBeVisible({ timeout: 10_000 });

        // Wait briefly for auto-apply
        await page.waitForTimeout(3_000);

        // If auto-apply didn't fire, manually click Apply in the PlotProposalSwitcher
        const proceedButton2 = page.locator("button:has-text('Proceed')").first();
        await proceedButton2.click();
        await page.waitForTimeout(1_000);

        // Check if we got "No Boundaries" — if so, manually apply
        const noBoundaries = await page.locator("button:has-text('No Boundaries')").isVisible({ timeout: 2_000 }).catch(() => false);
        if (noBoundaries) {
            console.log("  Auto-apply didn't fire, clicking Apply manually...");
            await page.waitForTimeout(2_000);

            // Check if the PlotProposalSwitcher panel is already expanded
            const panelVisible = await page.locator("text=Plot Grid Options").isVisible({ timeout: 2_000 }).catch(() => false);
            if (!panelVisible) {
                // Expand it by clicking the grid icon
                const gridIcon = page.locator("svg[data-testid='DashboardCustomizeIcon']").or(
                    page.locator("button:has(svg[data-testid='DashboardCustomizeIcon'])")
                );
                await gridIcon.first().click();
                await page.waitForTimeout(1_000);
            }

            await expect(page.locator("text=Plot Grid Options")).toBeVisible({ timeout: 5_000 });
            await page.locator("button:has-text('Apply')").click();
            await page.waitForTimeout(2_000);

            await proceedButton2.click();
            await page.waitForTimeout(2_000);
        }

        // Verify we advanced to Step 3
        await expect(page.locator("text=Get Plot Images").first()).toBeVisible({ timeout: 15_000 });
        console.log("✓ Step 2: Plot boundaries generated and proceeded");

        // ── Step 3: Get Plot Images (PlotImageExtractor) ─────────────────
        await expect(page.locator("text=Get Plot Images").first()).toBeVisible({ timeout: 15_000 });

        // Verify plot boundary count chip
        await expect(page.locator("text=4 plot boundaries defined")).toBeVisible({ timeout: 15_000 });

        // Wait for date dropdown to populate (checkForOdmOrthomosaic discovers our date)
        await expect(page.locator(`text=${FIELDS.date}`).first()).toBeVisible({ timeout: 30_000 });

        // Click "Split Orthomosaics Based on Plot Boundaries"
        const splitButton = page.locator("button:has-text('Split Orthomosaics')");
        await expect(splitButton).toBeVisible({ timeout: 10_000 });
        await expect(splitButton).toBeEnabled({ timeout: 10_000 });
        await splitButton.click();

        // Verify loading state
        await expect(page.locator("text=Splitting Orthomosaics")).toBeVisible({ timeout: 10_000 });
        console.log("✓ Step 3: Split job submitted, waiting for completion...");

        // Wait for success message (job runs asynchronously via worker)
        await expect(
            page.locator("text=Successfully extracted")
        ).toBeVisible({ timeout: 240_000 });

        console.log("✓ Step 3: Orthomosaic split completed");
        await page.screenshot({ path: "test-results/associate-plots-split-complete.png" });

        // Verify no critical errors
        expect(errors).toEqual([]);
    });

    test("verify plot images exist in MinIO", async ({ request }) => {
        const result = await listFilesInMinIO(request, PLOT_IMAGES_DIR);
        expect(result.status).toBe(200);
        expect(result.body).toBeTruthy();

        const files = Array.isArray(result.body) ? result.body : [];
        const pngFiles = files.filter(f => {
            const name = f.object_name || f.name || (typeof f === "string" ? f : "");
            return name.toLowerCase().endsWith(".png");
        });

        // Should have 4 plot images (one per auto-generated plot boundary)
        expect(pngFiles.length).toBe(4);

        // Verify filenames contain "plot_" prefix (from the worker naming convention)
        const fileNames = pngFiles.map(f => f.object_name || f.name || (typeof f === "string" ? f : ""));
        for (const name of fileNames) {
            expect(name).toContain("plot_");
            expect(name).toContain("accession_");
        }

        // Verify each file has actual content (> 1KB, not empty)
        for (const f of pngFiles) {
            const size = f.size || 0;
            if (size > 0) {
                expect(size).toBeGreaterThan(1000);
            }
        }

        console.log(`Verified ${pngFiles.length} plot images in MinIO:`, fileNames.map(n => n.split("/").pop()));
    });
});
