/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutConsoleRouteImport } from './routes/_layout/console'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProcessIndexRouteImport } from './routes/_layout/process/index'
import { Route as LayoutGenotypingIndexRouteImport } from './routes/_layout/genotyping/index'
import { Route as LayoutFilesIndexRouteImport } from './routes/_layout/files/index'
import { Route as LayoutAnalyzeIndexRouteImport } from './routes/_layout/analyze/index'
import { Route as LayoutAdminIndexRouteImport } from './routes/_layout/admin/index'
import { Route as LayoutProcessWorkspaceIdRouteImport } from './routes/_layout/process/$workspaceId'
import { Route as LayoutGenotypingStudyIdRouteImport } from './routes/_layout/genotyping/$studyId'
import { Route as LayoutAdminTraitsRouteImport } from './routes/_layout/admin/traits'
import { Route as LayoutAdminTraitLevelsRouteImport } from './routes/_layout/admin/trait-levels'
import { Route as LayoutAdminSitesRouteImport } from './routes/_layout/admin/sites'
import { Route as LayoutAdminSensorsRouteImport } from './routes/_layout/admin/sensors'
import { Route as LayoutAdminSensorTypesRouteImport } from './routes/_layout/admin/sensor-types'
import { Route as LayoutAdminSensorPlatformsRouteImport } from './routes/_layout/admin/sensor-platforms'
import { Route as LayoutAdminSeasonsRouteImport } from './routes/_layout/admin/seasons'
import { Route as LayoutAdminPopulationsRouteImport } from './routes/_layout/admin/populations'
import { Route as LayoutAdminLinesRouteImport } from './routes/_layout/admin/lines'
import { Route as LayoutAdminDatasetTypesRouteImport } from './routes/_layout/admin/dataset-types'
import { Route as LayoutAdminDataTypesRouteImport } from './routes/_layout/admin/data-types'
import { Route as LayoutAdminDataFormatsRouteImport } from './routes/_layout/admin/data-formats'
import { Route as LayoutAdminAccessionsRouteImport } from './routes/_layout/admin/accessions'
import { Route as LayoutProcessWorkspaceIdIndexRouteImport } from './routes/_layout/process/$workspaceId/index'
import { Route as LayoutProcessJobsJobIdRouteImport } from './routes/_layout/process/jobs.$jobId'
import { Route as LayoutProcessWorkspaceIdToolRouteImport } from './routes/_layout/process/$workspaceId/tool'
import { Route as LayoutProcessWorkspaceIdPipelineRouteImport } from './routes/_layout/process/$workspaceId/pipeline'
import { Route as LayoutProcessWorkspaceIdRunRunIdRouteImport } from './routes/_layout/process/$workspaceId/run/$runId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutConsoleRoute = LayoutConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProcessIndexRoute = LayoutProcessIndexRouteImport.update({
  id: '/process/',
  path: '/process/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGenotypingIndexRoute = LayoutGenotypingIndexRouteImport.update({
  id: '/genotyping/',
  path: '/genotyping/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesIndexRoute = LayoutFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyzeIndexRoute = LayoutAnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminIndexRoute = LayoutAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutProcessWorkspaceIdRoute =
  LayoutProcessWorkspaceIdRouteImport.update({
    id: '/process/$workspaceId',
    path: '/process/$workspaceId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutGenotypingStudyIdRoute = LayoutGenotypingStudyIdRouteImport.update({
  id: '/genotyping/$studyId',
  path: '/genotyping/$studyId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminTraitsRoute = LayoutAdminTraitsRouteImport.update({
  id: '/traits',
  path: '/traits',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminTraitLevelsRoute = LayoutAdminTraitLevelsRouteImport.update({
  id: '/trait-levels',
  path: '/trait-levels',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSitesRoute = LayoutAdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSensorsRoute = LayoutAdminSensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSensorTypesRoute = LayoutAdminSensorTypesRouteImport.update({
  id: '/sensor-types',
  path: '/sensor-types',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminSensorPlatformsRoute =
  LayoutAdminSensorPlatformsRouteImport.update({
    id: '/sensor-platforms',
    path: '/sensor-platforms',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminSeasonsRoute = LayoutAdminSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPopulationsRoute = LayoutAdminPopulationsRouteImport.update({
  id: '/populations',
  path: '/populations',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminLinesRoute = LayoutAdminLinesRouteImport.update({
  id: '/lines',
  path: '/lines',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminDatasetTypesRoute = LayoutAdminDatasetTypesRouteImport.update({
  id: '/dataset-types',
  path: '/dataset-types',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminDataTypesRoute = LayoutAdminDataTypesRouteImport.update({
  id: '/data-types',
  path: '/data-types',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminDataFormatsRoute = LayoutAdminDataFormatsRouteImport.update({
  id: '/data-formats',
  path: '/data-formats',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminAccessionsRoute = LayoutAdminAccessionsRouteImport.update({
  id: '/accessions',
  path: '/accessions',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutProcessWorkspaceIdIndexRoute =
  LayoutProcessWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)
const LayoutProcessJobsJobIdRoute = LayoutProcessJobsJobIdRouteImport.update({
  id: '/process/jobs/$jobId',
  path: '/process/jobs/$jobId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProcessWorkspaceIdToolRoute =
  LayoutProcessWorkspaceIdToolRouteImport.update({
    id: '/tool',
    path: '/tool',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)
const LayoutProcessWorkspaceIdPipelineRoute =
  LayoutProcessWorkspaceIdPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)
const LayoutProcessWorkspaceIdRunRunIdRoute =
  LayoutProcessWorkspaceIdRunRunIdRouteImport.update({
    id: '/run/$runId',
    path: '/run/$runId',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRouteWithChildren
  '/console': typeof LayoutConsoleRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/accessions': typeof LayoutAdminAccessionsRoute
  '/admin/data-formats': typeof LayoutAdminDataFormatsRoute
  '/admin/data-types': typeof LayoutAdminDataTypesRoute
  '/admin/dataset-types': typeof LayoutAdminDatasetTypesRoute
  '/admin/lines': typeof LayoutAdminLinesRoute
  '/admin/populations': typeof LayoutAdminPopulationsRoute
  '/admin/seasons': typeof LayoutAdminSeasonsRoute
  '/admin/sensor-platforms': typeof LayoutAdminSensorPlatformsRoute
  '/admin/sensor-types': typeof LayoutAdminSensorTypesRoute
  '/admin/sensors': typeof LayoutAdminSensorsRoute
  '/admin/sites': typeof LayoutAdminSitesRoute
  '/admin/trait-levels': typeof LayoutAdminTraitLevelsRoute
  '/admin/traits': typeof LayoutAdminTraitsRoute
  '/genotyping/$studyId': typeof LayoutGenotypingStudyIdRoute
  '/process/$workspaceId': typeof LayoutProcessWorkspaceIdRouteWithChildren
  '/admin/': typeof LayoutAdminIndexRoute
  '/analyze': typeof LayoutAnalyzeIndexRoute
  '/files': typeof LayoutFilesIndexRoute
  '/genotyping': typeof LayoutGenotypingIndexRoute
  '/process': typeof LayoutProcessIndexRoute
  '/process/$workspaceId/pipeline': typeof LayoutProcessWorkspaceIdPipelineRoute
  '/process/$workspaceId/tool': typeof LayoutProcessWorkspaceIdToolRoute
  '/process/jobs/$jobId': typeof LayoutProcessJobsJobIdRoute
  '/process/$workspaceId/': typeof LayoutProcessWorkspaceIdIndexRoute
  '/process/$workspaceId/run/$runId': typeof LayoutProcessWorkspaceIdRunRunIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/console': typeof LayoutConsoleRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/admin/accessions': typeof LayoutAdminAccessionsRoute
  '/admin/data-formats': typeof LayoutAdminDataFormatsRoute
  '/admin/data-types': typeof LayoutAdminDataTypesRoute
  '/admin/dataset-types': typeof LayoutAdminDatasetTypesRoute
  '/admin/lines': typeof LayoutAdminLinesRoute
  '/admin/populations': typeof LayoutAdminPopulationsRoute
  '/admin/seasons': typeof LayoutAdminSeasonsRoute
  '/admin/sensor-platforms': typeof LayoutAdminSensorPlatformsRoute
  '/admin/sensor-types': typeof LayoutAdminSensorTypesRoute
  '/admin/sensors': typeof LayoutAdminSensorsRoute
  '/admin/sites': typeof LayoutAdminSitesRoute
  '/admin/trait-levels': typeof LayoutAdminTraitLevelsRoute
  '/admin/traits': typeof LayoutAdminTraitsRoute
  '/genotyping/$studyId': typeof LayoutGenotypingStudyIdRoute
  '/admin': typeof LayoutAdminIndexRoute
  '/analyze': typeof LayoutAnalyzeIndexRoute
  '/files': typeof LayoutFilesIndexRoute
  '/genotyping': typeof LayoutGenotypingIndexRoute
  '/process': typeof LayoutProcessIndexRoute
  '/process/$workspaceId/pipeline': typeof LayoutProcessWorkspaceIdPipelineRoute
  '/process/$workspaceId/tool': typeof LayoutProcessWorkspaceIdToolRoute
  '/process/jobs/$jobId': typeof LayoutProcessJobsJobIdRoute
  '/process/$workspaceId': typeof LayoutProcessWorkspaceIdIndexRoute
  '/process/$workspaceId/run/$runId': typeof LayoutProcessWorkspaceIdRunRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/console': typeof LayoutConsoleRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/accessions': typeof LayoutAdminAccessionsRoute
  '/_layout/admin/data-formats': typeof LayoutAdminDataFormatsRoute
  '/_layout/admin/data-types': typeof LayoutAdminDataTypesRoute
  '/_layout/admin/dataset-types': typeof LayoutAdminDatasetTypesRoute
  '/_layout/admin/lines': typeof LayoutAdminLinesRoute
  '/_layout/admin/populations': typeof LayoutAdminPopulationsRoute
  '/_layout/admin/seasons': typeof LayoutAdminSeasonsRoute
  '/_layout/admin/sensor-platforms': typeof LayoutAdminSensorPlatformsRoute
  '/_layout/admin/sensor-types': typeof LayoutAdminSensorTypesRoute
  '/_layout/admin/sensors': typeof LayoutAdminSensorsRoute
  '/_layout/admin/sites': typeof LayoutAdminSitesRoute
  '/_layout/admin/trait-levels': typeof LayoutAdminTraitLevelsRoute
  '/_layout/admin/traits': typeof LayoutAdminTraitsRoute
  '/_layout/genotyping/$studyId': typeof LayoutGenotypingStudyIdRoute
  '/_layout/process/$workspaceId': typeof LayoutProcessWorkspaceIdRouteWithChildren
  '/_layout/admin/': typeof LayoutAdminIndexRoute
  '/_layout/analyze/': typeof LayoutAnalyzeIndexRoute
  '/_layout/files/': typeof LayoutFilesIndexRoute
  '/_layout/genotyping/': typeof LayoutGenotypingIndexRoute
  '/_layout/process/': typeof LayoutProcessIndexRoute
  '/_layout/process/$workspaceId/pipeline': typeof LayoutProcessWorkspaceIdPipelineRoute
  '/_layout/process/$workspaceId/tool': typeof LayoutProcessWorkspaceIdToolRoute
  '/_layout/process/jobs/$jobId': typeof LayoutProcessJobsJobIdRoute
  '/_layout/process/$workspaceId/': typeof LayoutProcessWorkspaceIdIndexRoute
  '/_layout/process/$workspaceId/run/$runId': typeof LayoutProcessWorkspaceIdRunRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/console'
    | '/items'
    | '/settings'
    | '/'
    | '/admin/accessions'
    | '/admin/data-formats'
    | '/admin/data-types'
    | '/admin/dataset-types'
    | '/admin/lines'
    | '/admin/populations'
    | '/admin/seasons'
    | '/admin/sensor-platforms'
    | '/admin/sensor-types'
    | '/admin/sensors'
    | '/admin/sites'
    | '/admin/trait-levels'
    | '/admin/traits'
    | '/genotyping/$studyId'
    | '/process/$workspaceId'
    | '/admin/'
    | '/analyze'
    | '/files'
    | '/genotyping'
    | '/process'
    | '/process/$workspaceId/pipeline'
    | '/process/$workspaceId/tool'
    | '/process/jobs/$jobId'
    | '/process/$workspaceId/'
    | '/process/$workspaceId/run/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/console'
    | '/items'
    | '/settings'
    | '/'
    | '/admin/accessions'
    | '/admin/data-formats'
    | '/admin/data-types'
    | '/admin/dataset-types'
    | '/admin/lines'
    | '/admin/populations'
    | '/admin/seasons'
    | '/admin/sensor-platforms'
    | '/admin/sensor-types'
    | '/admin/sensors'
    | '/admin/sites'
    | '/admin/trait-levels'
    | '/admin/traits'
    | '/genotyping/$studyId'
    | '/admin'
    | '/analyze'
    | '/files'
    | '/genotyping'
    | '/process'
    | '/process/$workspaceId/pipeline'
    | '/process/$workspaceId/tool'
    | '/process/jobs/$jobId'
    | '/process/$workspaceId'
    | '/process/$workspaceId/run/$runId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/console'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/admin/accessions'
    | '/_layout/admin/data-formats'
    | '/_layout/admin/data-types'
    | '/_layout/admin/dataset-types'
    | '/_layout/admin/lines'
    | '/_layout/admin/populations'
    | '/_layout/admin/seasons'
    | '/_layout/admin/sensor-platforms'
    | '/_layout/admin/sensor-types'
    | '/_layout/admin/sensors'
    | '/_layout/admin/sites'
    | '/_layout/admin/trait-levels'
    | '/_layout/admin/traits'
    | '/_layout/genotyping/$studyId'
    | '/_layout/process/$workspaceId'
    | '/_layout/admin/'
    | '/_layout/analyze/'
    | '/_layout/files/'
    | '/_layout/genotyping/'
    | '/_layout/process/'
    | '/_layout/process/$workspaceId/pipeline'
    | '/_layout/process/$workspaceId/tool'
    | '/_layout/process/jobs/$jobId'
    | '/_layout/process/$workspaceId/'
    | '/_layout/process/$workspaceId/run/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/console': {
      id: '/_layout/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof LayoutConsoleRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/process/': {
      id: '/_layout/process/'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof LayoutProcessIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/genotyping/': {
      id: '/_layout/genotyping/'
      path: '/genotyping'
      fullPath: '/genotyping'
      preLoaderRoute: typeof LayoutGenotypingIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files/': {
      id: '/_layout/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof LayoutFilesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analyze/': {
      id: '/_layout/analyze/'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof LayoutAnalyzeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/': {
      id: '/_layout/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAdminIndexRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/process/$workspaceId': {
      id: '/_layout/process/$workspaceId'
      path: '/process/$workspaceId'
      fullPath: '/process/$workspaceId'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/genotyping/$studyId': {
      id: '/_layout/genotyping/$studyId'
      path: '/genotyping/$studyId'
      fullPath: '/genotyping/$studyId'
      preLoaderRoute: typeof LayoutGenotypingStudyIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin/traits': {
      id: '/_layout/admin/traits'
      path: '/traits'
      fullPath: '/admin/traits'
      preLoaderRoute: typeof LayoutAdminTraitsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/trait-levels': {
      id: '/_layout/admin/trait-levels'
      path: '/trait-levels'
      fullPath: '/admin/trait-levels'
      preLoaderRoute: typeof LayoutAdminTraitLevelsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/sites': {
      id: '/_layout/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof LayoutAdminSitesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/sensors': {
      id: '/_layout/admin/sensors'
      path: '/sensors'
      fullPath: '/admin/sensors'
      preLoaderRoute: typeof LayoutAdminSensorsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/sensor-types': {
      id: '/_layout/admin/sensor-types'
      path: '/sensor-types'
      fullPath: '/admin/sensor-types'
      preLoaderRoute: typeof LayoutAdminSensorTypesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/sensor-platforms': {
      id: '/_layout/admin/sensor-platforms'
      path: '/sensor-platforms'
      fullPath: '/admin/sensor-platforms'
      preLoaderRoute: typeof LayoutAdminSensorPlatformsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/seasons': {
      id: '/_layout/admin/seasons'
      path: '/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof LayoutAdminSeasonsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/populations': {
      id: '/_layout/admin/populations'
      path: '/populations'
      fullPath: '/admin/populations'
      preLoaderRoute: typeof LayoutAdminPopulationsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/lines': {
      id: '/_layout/admin/lines'
      path: '/lines'
      fullPath: '/admin/lines'
      preLoaderRoute: typeof LayoutAdminLinesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/dataset-types': {
      id: '/_layout/admin/dataset-types'
      path: '/dataset-types'
      fullPath: '/admin/dataset-types'
      preLoaderRoute: typeof LayoutAdminDatasetTypesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/data-types': {
      id: '/_layout/admin/data-types'
      path: '/data-types'
      fullPath: '/admin/data-types'
      preLoaderRoute: typeof LayoutAdminDataTypesRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/data-formats': {
      id: '/_layout/admin/data-formats'
      path: '/data-formats'
      fullPath: '/admin/data-formats'
      preLoaderRoute: typeof LayoutAdminDataFormatsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/accessions': {
      id: '/_layout/admin/accessions'
      path: '/accessions'
      fullPath: '/admin/accessions'
      preLoaderRoute: typeof LayoutAdminAccessionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/process/$workspaceId/': {
      id: '/_layout/process/$workspaceId/'
      path: '/'
      fullPath: '/process/$workspaceId/'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
    '/_layout/process/jobs/$jobId': {
      id: '/_layout/process/jobs/$jobId'
      path: '/process/jobs/$jobId'
      fullPath: '/process/jobs/$jobId'
      preLoaderRoute: typeof LayoutProcessJobsJobIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/process/$workspaceId/tool': {
      id: '/_layout/process/$workspaceId/tool'
      path: '/tool'
      fullPath: '/process/$workspaceId/tool'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdToolRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
    '/_layout/process/$workspaceId/pipeline': {
      id: '/_layout/process/$workspaceId/pipeline'
      path: '/pipeline'
      fullPath: '/process/$workspaceId/pipeline'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdPipelineRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
    '/_layout/process/$workspaceId/run/$runId': {
      id: '/_layout/process/$workspaceId/run/$runId'
      path: '/run/$runId'
      fullPath: '/process/$workspaceId/run/$runId'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdRunRunIdRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminAccessionsRoute: typeof LayoutAdminAccessionsRoute
  LayoutAdminDataFormatsRoute: typeof LayoutAdminDataFormatsRoute
  LayoutAdminDataTypesRoute: typeof LayoutAdminDataTypesRoute
  LayoutAdminDatasetTypesRoute: typeof LayoutAdminDatasetTypesRoute
  LayoutAdminLinesRoute: typeof LayoutAdminLinesRoute
  LayoutAdminPopulationsRoute: typeof LayoutAdminPopulationsRoute
  LayoutAdminSeasonsRoute: typeof LayoutAdminSeasonsRoute
  LayoutAdminSensorPlatformsRoute: typeof LayoutAdminSensorPlatformsRoute
  LayoutAdminSensorTypesRoute: typeof LayoutAdminSensorTypesRoute
  LayoutAdminSensorsRoute: typeof LayoutAdminSensorsRoute
  LayoutAdminSitesRoute: typeof LayoutAdminSitesRoute
  LayoutAdminTraitLevelsRoute: typeof LayoutAdminTraitLevelsRoute
  LayoutAdminTraitsRoute: typeof LayoutAdminTraitsRoute
  LayoutAdminIndexRoute: typeof LayoutAdminIndexRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminAccessionsRoute: LayoutAdminAccessionsRoute,
  LayoutAdminDataFormatsRoute: LayoutAdminDataFormatsRoute,
  LayoutAdminDataTypesRoute: LayoutAdminDataTypesRoute,
  LayoutAdminDatasetTypesRoute: LayoutAdminDatasetTypesRoute,
  LayoutAdminLinesRoute: LayoutAdminLinesRoute,
  LayoutAdminPopulationsRoute: LayoutAdminPopulationsRoute,
  LayoutAdminSeasonsRoute: LayoutAdminSeasonsRoute,
  LayoutAdminSensorPlatformsRoute: LayoutAdminSensorPlatformsRoute,
  LayoutAdminSensorTypesRoute: LayoutAdminSensorTypesRoute,
  LayoutAdminSensorsRoute: LayoutAdminSensorsRoute,
  LayoutAdminSitesRoute: LayoutAdminSitesRoute,
  LayoutAdminTraitLevelsRoute: LayoutAdminTraitLevelsRoute,
  LayoutAdminTraitsRoute: LayoutAdminTraitsRoute,
  LayoutAdminIndexRoute: LayoutAdminIndexRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutProcessWorkspaceIdRouteChildren {
  LayoutProcessWorkspaceIdPipelineRoute: typeof LayoutProcessWorkspaceIdPipelineRoute
  LayoutProcessWorkspaceIdToolRoute: typeof LayoutProcessWorkspaceIdToolRoute
  LayoutProcessWorkspaceIdIndexRoute: typeof LayoutProcessWorkspaceIdIndexRoute
  LayoutProcessWorkspaceIdRunRunIdRoute: typeof LayoutProcessWorkspaceIdRunRunIdRoute
}

const LayoutProcessWorkspaceIdRouteChildren: LayoutProcessWorkspaceIdRouteChildren =
  {
    LayoutProcessWorkspaceIdPipelineRoute:
      LayoutProcessWorkspaceIdPipelineRoute,
    LayoutProcessWorkspaceIdToolRoute: LayoutProcessWorkspaceIdToolRoute,
    LayoutProcessWorkspaceIdIndexRoute: LayoutProcessWorkspaceIdIndexRoute,
    LayoutProcessWorkspaceIdRunRunIdRoute:
      LayoutProcessWorkspaceIdRunRunIdRoute,
  }

const LayoutProcessWorkspaceIdRouteWithChildren =
  LayoutProcessWorkspaceIdRoute._addFileChildren(
    LayoutProcessWorkspaceIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutConsoleRoute: typeof LayoutConsoleRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutGenotypingStudyIdRoute: typeof LayoutGenotypingStudyIdRoute
  LayoutProcessWorkspaceIdRoute: typeof LayoutProcessWorkspaceIdRouteWithChildren
  LayoutAnalyzeIndexRoute: typeof LayoutAnalyzeIndexRoute
  LayoutFilesIndexRoute: typeof LayoutFilesIndexRoute
  LayoutGenotypingIndexRoute: typeof LayoutGenotypingIndexRoute
  LayoutProcessIndexRoute: typeof LayoutProcessIndexRoute
  LayoutProcessJobsJobIdRoute: typeof LayoutProcessJobsJobIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutConsoleRoute: LayoutConsoleRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutGenotypingStudyIdRoute: LayoutGenotypingStudyIdRoute,
  LayoutProcessWorkspaceIdRoute: LayoutProcessWorkspaceIdRouteWithChildren,
  LayoutAnalyzeIndexRoute: LayoutAnalyzeIndexRoute,
  LayoutFilesIndexRoute: LayoutFilesIndexRoute,
  LayoutGenotypingIndexRoute: LayoutGenotypingIndexRoute,
  LayoutProcessIndexRoute: LayoutProcessIndexRoute,
  LayoutProcessJobsJobIdRoute: LayoutProcessJobsJobIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
