/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProcessIndexRouteImport } from './routes/_layout/process/index'
import { Route as LayoutAnalyzeIndexRouteImport } from './routes/_layout/analyze/index'
import { Route as LayoutProcessWorkspaceIdRouteImport } from './routes/_layout/process/$workspaceId'
import { Route as LayoutFilesUpload_dataRouteImport } from './routes/_layout/files/upload_data'
import { Route as LayoutFilesManage_dataRouteImport } from './routes/_layout/files/manage_data'
import { Route as LayoutAnalyzeRunIdRouteImport } from './routes/_layout/analyze/$runId'
import { Route as LayoutProcessWorkspaceIdIndexRouteImport } from './routes/_layout/process/$workspaceId/index'
import { Route as LayoutProcessWorkspaceIdToolRouteImport } from './routes/_layout/process/$workspaceId/tool'
import { Route as LayoutProcessWorkspaceIdPipelineRouteImport } from './routes/_layout/process/$workspaceId/pipeline'
import { Route as LayoutProcessWorkspaceIdRunRunIdRouteImport } from './routes/_layout/process/$workspaceId/run/$runId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProcessIndexRoute = LayoutProcessIndexRouteImport.update({
  id: '/process/',
  path: '/process/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyzeIndexRoute = LayoutAnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProcessWorkspaceIdRoute =
  LayoutProcessWorkspaceIdRouteImport.update({
    id: '/process/$workspaceId',
    path: '/process/$workspaceId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutFilesUpload_dataRoute = LayoutFilesUpload_dataRouteImport.update({
  id: '/files/upload_data',
  path: '/files/upload_data',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFilesManage_dataRoute = LayoutFilesManage_dataRouteImport.update({
  id: '/files/manage_data',
  path: '/files/manage_data',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalyzeRunIdRoute = LayoutAnalyzeRunIdRouteImport.update({
  id: '/analyze/$runId',
  path: '/analyze/$runId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProcessWorkspaceIdIndexRoute =
  LayoutProcessWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)
const LayoutProcessWorkspaceIdToolRoute =
  LayoutProcessWorkspaceIdToolRouteImport.update({
    id: '/tool',
    path: '/tool',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)
const LayoutProcessWorkspaceIdPipelineRoute =
  LayoutProcessWorkspaceIdPipelineRouteImport.update({
    id: '/pipeline',
    path: '/pipeline',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)
const LayoutProcessWorkspaceIdRunRunIdRoute =
  LayoutProcessWorkspaceIdRunRunIdRouteImport.update({
    id: '/run/$runId',
    path: '/run/$runId',
    getParentRoute: () => LayoutProcessWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/analyze/$runId': typeof LayoutAnalyzeRunIdRoute
  '/files/manage_data': typeof LayoutFilesManage_dataRoute
  '/files/upload_data': typeof LayoutFilesUpload_dataRoute
  '/process/$workspaceId': typeof LayoutProcessWorkspaceIdRouteWithChildren
  '/analyze': typeof LayoutAnalyzeIndexRoute
  '/process': typeof LayoutProcessIndexRoute
  '/process/$workspaceId/pipeline': typeof LayoutProcessWorkspaceIdPipelineRoute
  '/process/$workspaceId/tool': typeof LayoutProcessWorkspaceIdToolRoute
  '/process/$workspaceId/': typeof LayoutProcessWorkspaceIdIndexRoute
  '/process/$workspaceId/run/$runId': typeof LayoutProcessWorkspaceIdRunRunIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/analyze/$runId': typeof LayoutAnalyzeRunIdRoute
  '/files/manage_data': typeof LayoutFilesManage_dataRoute
  '/files/upload_data': typeof LayoutFilesUpload_dataRoute
  '/analyze': typeof LayoutAnalyzeIndexRoute
  '/process': typeof LayoutProcessIndexRoute
  '/process/$workspaceId/pipeline': typeof LayoutProcessWorkspaceIdPipelineRoute
  '/process/$workspaceId/tool': typeof LayoutProcessWorkspaceIdToolRoute
  '/process/$workspaceId': typeof LayoutProcessWorkspaceIdIndexRoute
  '/process/$workspaceId/run/$runId': typeof LayoutProcessWorkspaceIdRunRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/analyze/$runId': typeof LayoutAnalyzeRunIdRoute
  '/_layout/files/manage_data': typeof LayoutFilesManage_dataRoute
  '/_layout/files/upload_data': typeof LayoutFilesUpload_dataRoute
  '/_layout/process/$workspaceId': typeof LayoutProcessWorkspaceIdRouteWithChildren
  '/_layout/analyze/': typeof LayoutAnalyzeIndexRoute
  '/_layout/process/': typeof LayoutProcessIndexRoute
  '/_layout/process/$workspaceId/pipeline': typeof LayoutProcessWorkspaceIdPipelineRoute
  '/_layout/process/$workspaceId/tool': typeof LayoutProcessWorkspaceIdToolRoute
  '/_layout/process/$workspaceId/': typeof LayoutProcessWorkspaceIdIndexRoute
  '/_layout/process/$workspaceId/run/$runId': typeof LayoutProcessWorkspaceIdRunRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/analyze/$runId'
    | '/files/manage_data'
    | '/files/upload_data'
    | '/process/$workspaceId'
    | '/analyze'
    | '/process'
    | '/process/$workspaceId/pipeline'
    | '/process/$workspaceId/tool'
    | '/process/$workspaceId/'
    | '/process/$workspaceId/run/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/settings'
    | '/'
    | '/analyze/$runId'
    | '/files/manage_data'
    | '/files/upload_data'
    | '/analyze'
    | '/process'
    | '/process/$workspaceId/pipeline'
    | '/process/$workspaceId/tool'
    | '/process/$workspaceId'
    | '/process/$workspaceId/run/$runId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/analyze/$runId'
    | '/_layout/files/manage_data'
    | '/_layout/files/upload_data'
    | '/_layout/process/$workspaceId'
    | '/_layout/analyze/'
    | '/_layout/process/'
    | '/_layout/process/$workspaceId/pipeline'
    | '/_layout/process/$workspaceId/tool'
    | '/_layout/process/$workspaceId/'
    | '/_layout/process/$workspaceId/run/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/process/': {
      id: '/_layout/process/'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof LayoutProcessIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analyze/': {
      id: '/_layout/analyze/'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof LayoutAnalyzeIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/process/$workspaceId': {
      id: '/_layout/process/$workspaceId'
      path: '/process/$workspaceId'
      fullPath: '/process/$workspaceId'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files/upload_data': {
      id: '/_layout/files/upload_data'
      path: '/files/upload_data'
      fullPath: '/files/upload_data'
      preLoaderRoute: typeof LayoutFilesUpload_dataRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/files/manage_data': {
      id: '/_layout/files/manage_data'
      path: '/files/manage_data'
      fullPath: '/files/manage_data'
      preLoaderRoute: typeof LayoutFilesManage_dataRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analyze/$runId': {
      id: '/_layout/analyze/$runId'
      path: '/analyze/$runId'
      fullPath: '/analyze/$runId'
      preLoaderRoute: typeof LayoutAnalyzeRunIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/process/$workspaceId/': {
      id: '/_layout/process/$workspaceId/'
      path: '/'
      fullPath: '/process/$workspaceId/'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
    '/_layout/process/$workspaceId/tool': {
      id: '/_layout/process/$workspaceId/tool'
      path: '/tool'
      fullPath: '/process/$workspaceId/tool'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdToolRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
    '/_layout/process/$workspaceId/pipeline': {
      id: '/_layout/process/$workspaceId/pipeline'
      path: '/pipeline'
      fullPath: '/process/$workspaceId/pipeline'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdPipelineRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
    '/_layout/process/$workspaceId/run/$runId': {
      id: '/_layout/process/$workspaceId/run/$runId'
      path: '/run/$runId'
      fullPath: '/process/$workspaceId/run/$runId'
      preLoaderRoute: typeof LayoutProcessWorkspaceIdRunRunIdRouteImport
      parentRoute: typeof LayoutProcessWorkspaceIdRoute
    }
  }
}

interface LayoutProcessWorkspaceIdRouteChildren {
  LayoutProcessWorkspaceIdPipelineRoute: typeof LayoutProcessWorkspaceIdPipelineRoute
  LayoutProcessWorkspaceIdToolRoute: typeof LayoutProcessWorkspaceIdToolRoute
  LayoutProcessWorkspaceIdIndexRoute: typeof LayoutProcessWorkspaceIdIndexRoute
  LayoutProcessWorkspaceIdRunRunIdRoute: typeof LayoutProcessWorkspaceIdRunRunIdRoute
}

const LayoutProcessWorkspaceIdRouteChildren: LayoutProcessWorkspaceIdRouteChildren =
  {
    LayoutProcessWorkspaceIdPipelineRoute:
      LayoutProcessWorkspaceIdPipelineRoute,
    LayoutProcessWorkspaceIdToolRoute: LayoutProcessWorkspaceIdToolRoute,
    LayoutProcessWorkspaceIdIndexRoute: LayoutProcessWorkspaceIdIndexRoute,
    LayoutProcessWorkspaceIdRunRunIdRoute:
      LayoutProcessWorkspaceIdRunRunIdRoute,
  }

const LayoutProcessWorkspaceIdRouteWithChildren =
  LayoutProcessWorkspaceIdRoute._addFileChildren(
    LayoutProcessWorkspaceIdRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAnalyzeRunIdRoute: typeof LayoutAnalyzeRunIdRoute
  LayoutFilesManage_dataRoute: typeof LayoutFilesManage_dataRoute
  LayoutFilesUpload_dataRoute: typeof LayoutFilesUpload_dataRoute
  LayoutProcessWorkspaceIdRoute: typeof LayoutProcessWorkspaceIdRouteWithChildren
  LayoutAnalyzeIndexRoute: typeof LayoutAnalyzeIndexRoute
  LayoutProcessIndexRoute: typeof LayoutProcessIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAnalyzeRunIdRoute: LayoutAnalyzeRunIdRoute,
  LayoutFilesManage_dataRoute: LayoutFilesManage_dataRoute,
  LayoutFilesUpload_dataRoute: LayoutFilesUpload_dataRoute,
  LayoutProcessWorkspaceIdRoute: LayoutProcessWorkspaceIdRouteWithChildren,
  LayoutAnalyzeIndexRoute: LayoutAnalyzeIndexRoute,
  LayoutProcessIndexRoute: LayoutProcessIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
